# FIPS-140-3 192bit
# Goal: Provide 192-bit security.
# Hash: sha-384
# RSA: >= 8192 bit
# ECDSA: 384-bit - 521-bit
# Reference: NIST SP 800-57, Table 2 on Page 54-55, Table 3 on Page 56
---
Settings:
  CryptoLibrary: native

Profiles:
  - Name: FIPS-140-3-192bit
    API:
      HashData:
        HashAlg: sha-384
      SignCertificate:
        SignAlg: ecdsa
        HashAlg: sha-384
        Validity:
          ValidNotBeforeOffset: -1h
          ValidNotAfterOffset: 8760h
        KeyConstraints:
          Subject:
            RSA:
              MinKeySize: 8192
              MaxKeySize: 15380
            ECDSA:
              MinKeySize: 384
              MaxKeySize: 521
          Issuer:
            ECDSA:
              MinKeySize: 384
              MaxKeySize: 521
        KeyUsage: [digitalSignature, keyEncipherment]
        ExtendedKeyUsage: [clientAuth]
        BasicConstraints:
          CA: false
