//go:build !ignore_autogenerated

package main

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *CryptoBroker) DeepCopyInto(out *CryptoBroker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy copies the receiver, creating a new CryptoBroker.
func (in *CryptoBroker) DeepCopy() *CryptoBroker {
	if in == nil {
		return nil
	}
	out := new(CryptoBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject copies the receiver, creating a new runtime.Object.
func (in *CryptoBroker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *CryptoBrokerStatus) DeepCopyInto(out *CryptoBrokerStatus) {
	*out = *in
	if in.ProfileDetails != nil {
		in, out := &in.ProfileDetails, &out.ProfileDetails
		*out = new(ProfileDetails)
		**out = **in
	}
}

// DeepCopy copies the receiver, creating a new CryptoBrokerStatus.
func (in *CryptoBrokerStatus) DeepCopy() *CryptoBrokerStatus {
	if in == nil {
		return nil
	}
	out := new(CryptoBrokerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *ProfileDetails) DeepCopyInto(out *ProfileDetails) {
	*out = *in
}

// DeepCopy copies the receiver, creating a new ProfileDetails.
func (in *ProfileDetails) DeepCopy() *ProfileDetails {
	if in == nil {
		return nil
	}
	out := new(ProfileDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver, writing into out. in must be non-nil.
func (in *CryptoBrokerList) DeepCopyInto(out *CryptoBrokerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CryptoBroker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy copies the receiver, creating a new CryptoBrokerList.
func (in *CryptoBrokerList) DeepCopy() *CryptoBrokerList {
	if in == nil {
		return nil
	}
	out := new(CryptoBrokerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject copies the receiver, creating a new runtime.Object.
func (in *CryptoBrokerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
